import { NewCharacter } from '@api/lib/ZodCharacter'; // adjust as needed

export const defaultValuesCharacter: Partial<NewCharacter> = {
	fullname: '',
	bio: {
		creator: '',
		owner: '',
		campaign: '',
		name: '',
		species: '',
		surname: null,
		subspecies: null,
		fighterType: null,
		isBoss: false,
		isCaster: false,
		isPun: false,
		isDead: false,
		avatar: {
			path: null,
			url: null,
		},
	},
	specifics: {
		size: 'average',
		alignment: 'neutral',
		gender: null,
		sizeBonus: 0,
		background: '',
		description: '',
		age: 0,
		weight: 0,
		height: 0,
		bornIn: '',
		restBonus: 0,
		dmgBonus: {
			ranged: null,
			fighting: null,
			brawling: null,
			defense: null,
			sneak: null,
			critical: null,
			magical: null,
		},
		massive: false,
	},
	path: {
		magicDomain: [],
		tree: null,
		careers: [],
		skills: [],
		feats: [],
		actions: [],
		attackType: '',
		defenseType: '',
		actionList: null,
		skillPoints: 0,
	},
	profile: {
		level: 1,
		experience: 0,
		glory: 0,
		luck: 0,
		destiny: 0,
		stats: {
			CEL: 0,
			AGI: 0,
			DEX: 0,
			STR: 0,
			END: 0,
			VIT: 0,
			WIL: 0,
			INS: 0,
			SEN: 0,
			CHA: 0,
			SOC: 0,
			ERU: 0,
		},
		statsStarting: {
			CEL: 0,
			AGI: 0,
			DEX: 0,
			STR: 0,
			END: 0,
			VIT: 0,
			WIL: 0,
			INS: 0,
			SEN: 0,
			CHA: 0,
			SOC: 0,
			ERU: 0,
		},
		speed: {
			crawling: 0,
			walking: 0,
			running: 0,
			obstacle: 0,
		},
		variables: {
			initiative: 0,
			attack: 0,
			brawl: 0,
			defense: 0,
			ranged: 0,
			perception: 0,
			discretion: 0,
			magic: 0,
			bravery: 0,
			survival: 0,
			enigms: 0,
			speech: 0,
			trade: 0,
			performance: 0,
			intimidation: 0,
		},
		boni: {
			initiative: 0,
			attack: 0,
			brawl: 0,
			defense: 0,
			ranged: 0,
			perception: 0,
			discretion: 0,
			magic: 0,
			bravery: 0,
			survival: 0,
			enigms: 0,
			speech: 0,
			trade: 0,
			performance: 0,
			intimidation: 0,
		},
	},
	status: {
		weightBonus: 0,
		carryWeight: 0,
		weightClass: 0,
		exhaustion: 0,
		gold: 0,
		equipmentValue: 0,
		tempHealth: null,
		tempSpirit: null,
		advantages: null,
		weight: { current: 0, max: 0 },
		health: { current: 0, max: 0 },
		spirit: { current: 0, max: 0 },
		magicLoad: { current: 0, max: 0 },
	},
	masteries: {
		crafting: { current: 0, max: 0 },
		fighting: { current: 0, max: 0 },
		defense: { current: 0, max: 0 },
		detection: { current: 0, max: 0 },
		discretion: { current: 0, max: 0 },
		speech: { current: 0, max: 0 },
		esoterism: { current: 0, max: 0 },
		logic: { current: 0, max: 0 },
		brawl: { current: 0, max: 0 },
		magic: { current: 0, max: 0 },
		preciseness: { current: 0, max: 0 },
		movement: { current: 0, max: 0 },
		trading: { current: 0, max: 0 },
		perception: { current: 0, max: 0 },
		performance: { current: 0, max: 0 },
		persuasion: { current: 0, max: 0 },
		physique: { current: 0, max: 0 },
		knowledge: { current: 0, max: 0 },
		sciences: { current: 0, max: 0 },
		healing: { current: 0, max: 0 },
		survival: { current: 0, max: 0 },
		ranged: { current: 0, max: 0 },
	},
	equipment: {
		weapons: [],
		armors: [],
		items: [],
		components: [],
		armorValue: 0,
		armorClass: 0,
	},
};
