name: Test Deploy

on:
  push:
    branches:
      - dev
  
jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apps/web'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true
          dest: ~/setup-pnpm
      
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        env: 
          VITE_API_URL: ${{ secrets.VITE_API_URL}}
